config/routes.rb
Rails.application.routes.draw do

  get 'souscrire', to: 'subscriptions#new'
  get 'comment-souscrire', to: redirect('/pourquoi-souscrire')

  resources :subscriptions, only: [:index, :new, :create, :edit, :update, :show], path: 'souscriptions' do
    get :confirm, on: :member, path: 'confirmation'
    get :document, on: :member, path: 'bulletin'
    get :members, on: :collection
    get :member, on: :collection
    get :rankings, on: :collection
    get :proportions, on: :collection
    get :regions, on: :collection
    get :share, on: :member, path: 'partager'
    get :widget, on: :member
    patch :update_widget, on: :member
  end

  devise_for :users, path: 'administration', controllers: {omniauth_callbacks: 'users/omniauth_callbacks'},
             path_names: {sign_in: 'connexion', sign_out: 'deconnexion'}

  scope module: 'admin' do
    scope '/administration' do
      resources :subscriptions, only: [:index, :update], path: 'souscriptions', as: 'subs' do
        get :sync_crm, on: :member
        post :send_mail, on: :member
      end
    end
  end

  mount Sibu::Engine, at: '/'

  root to: redirect('/404.html')
end

app/views/shared/_admin_content.html.erb
<div id="site_content" class="w100 mw1140p center pam sibu_site_content">
  <%= yield %>
</div>

app/views/shared/_admin_footer.html.erb
<div id="notifs"><%= render 'shared/notifications' %></div>

app/views/shared/_admin_header.html.erb
<header class="w100 admin_header">
  <div id="site_header" class="w100 mw1140p center flex-container aic">
    <%= link_to image_tag('logo_apidae.png', class: 'item-center w200p'), '/' %>
    <div class="txtright item-fluid lh">
      <%= link_to 'Gestion du site', sibu.sites_path, class: 'btn btn--info' %>
      <%= link_to 'Souscriptions', main_app.subs_path, class: 'btn btn--primary' %>
      <%= link_to 'Déconnexion', main_app.destroy_user_session_path, method: :delete, class: 'btn btn--outline btn--inverse' %>
    </div>
  </div>
</header>

app/views/shared/_crm_links.html.erb
<% if @subscription.opportunity_id %>
  <a href="https://www.sellsy.fr/prospection/opportunities/<%= @subscription.opportunity_id %>" target="_blank" class="bg--inverse pas mbm">
    <i class="fas fa-link fa-2x"></i>
  </a>
<% end %>
<%= button_to 'Mettre à jour'.html_safe, sync_crm_sub_path(@subscription), remote: true, method: :get,
            data: {confirm: 'Enregistrer la souscription dans la base GRC ?', disable_with: 'En cours...'},
              id: 'sync_crm_link', class: 'bg--danger pas' %>
<% unless @subscription.crm_history.blank? %>
  <button class="js-modal bg--primary pas mtm" data-modal-prefix-class="simple-animated"
          data-modal-content-id="crm_history_modal" data-modal-describedby-id="crm_history_description"
          data-modal-title="Dernière mise à jour CRM" data-modal-close-text="Fermer" data-modal-close-title="Fermer la fenêtre"
          aria-haspopup="dialog">
    <i class="fas fa-history fa-2x"></i>
  </button>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg--primary pam u-txt-center">
  <div class="w100 mw1140p center pbl">
    <div id="media_links" class="txtcenter u-bigger">
      <a href="https://www.linkedin.com/company/apidae-tourisme/" target="_blank">
        <i class="fab fa-linkedin-in"></i>
      </a>
      <a href="https://fr-fr.facebook.com/reseauApidae/" target="_blank">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="https://www.youtube.com/channel/UCSeGFcMYc4QSEbywxSHfRPw" target="_blank">
        <i class="fab fa-youtube"></i>
      </a>
    </div>
    <p class="mts txtcenter fw500">Suivez-nous</p>
    <div id="footer_links" class="mtl fw500">
      <a href="/mentions-legales">Mentions légales</a>
      <a href="https://www.apidae-tourisme.com" target="_blank">Qui sommes-nous ?</a>
      <a href="/contact">Contact</a>
      <a href="/faq">FAQ</a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<% if controller_name == 'pages' %>
  <div id="site_header" class="w100 mw1140p center flex-container aic" <%= sibu_attrs('header') %>>
    <%= link_to image_tag('logo_apidae.png', class: 'item-center'), '/' %>
    <%= site.p('header_title', class: 'h3-like lh') %>
    <a href="/devenir-societaire" class="apidae_btn_solid mlm mrs">Devenir sociétaire</a>
  </div>
<% else %>
  <div id="site_header" class="w100 mw1140p center flex-container aic">
    <%= link_to image_tag('logo_apidae.png', class: 'item-center'), '/' %>
    <a href="/devenir-societaire" class="apidae_btn_solid mlm mrs">Devenir sociétaire</a>
  </div>
<% end %>

app/views/shared/_hexa_img.html.erb
<!-- Note: expects a square image -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 117.74 133.15" style="width: <%= width %>;">
  <g>
    <clipPath id="hexa_mask">
      <path class="cls-1" d="M117.74,94.71V38.38a10.23,10.23,0,0,0-5.1-8.75L64,1.38a10.07,10.07,0,0,0-10.18,0L5.1,29.54A10.23,10.23,0,0,0,0,38.3V94.76a10.23,10.23,0,0,0,5.1,8.75L53.8,131.77a10.07,10.07,0,0,0,10.18,0l48.7-28.16a10.36,10.36,0,0,0,5-8.89"/>
    </clipPath>
  </g>
  <image clip-path="url(#hexa_mask)" width="134" height="134" xlink:href="<%= image_path(image) %>" />
</svg>

app/views/shared/_notifications.html.erb
<% if notice %>
  <p id="notice" class="w100 alert--success txtcenter"><%= notice %></p>
<% end %>
<% if alert %>
  <p id="alert" class="w100 alert--danger txtcenter"><%= alert %></p>
<% end %>

<% content_for :scripts do %>
  <script>
      displayAlerts();
  </script>
<% end %>