config/routes.rb
Rails.application.routes.draw do

  get 'souscrire', to: 'subscriptions#new'
  get 'comment-souscrire', to: redirect('/pourquoi-souscrire')

  resources :subscriptions, only: [:index, :new, :create, :edit, :update, :show], path: 'souscriptions' do
    get :confirm, on: :member, path: 'confirmation'
    get :document, on: :member, path: 'bulletin'
    get :members, on: :collection
    get :member, on: :collection
    get :rankings, on: :collection
    get :proportions, on: :collection
    get :regions, on: :collection
    get :share, on: :member, path: 'partager'
    get :widget, on: :member
    patch :update_widget, on: :member
  end

  devise_for :users, path: 'administration', controllers: {omniauth_callbacks: 'users/omniauth_callbacks'},
             path_names: {sign_in: 'connexion', sign_out: 'deconnexion'}

  scope module: 'admin' do
    scope '/administration' do
      resources :subscriptions, only: [:index, :update], path: 'souscriptions', as: 'subs' do
        get :sync_crm, on: :member
        post :send_mail, on: :member
      end
    end
  end

  mount Sibu::Engine, at: '/'

  root to: redirect('/404.html')
end

app/models/subscription.rb
require 'sellsy'

class Subscription < ApplicationRecord
  include AASM
  include Obfuscable

  has_one_attached :signature
  has_many :sponsored, class_name: "Subscription", foreign_key: :sponsor_id
  belongs_to :sponsor, class_name: "Subscription", optional: true

  store_accessor :structure_data, :structure_name, :siret, :ape, :legal_type, :legal_type_desc, :apidae_member_id, :widget_hosts
  store_accessor :person_data, :title, :first_name, :last_name, :role, :birth_date, :address, :postal_code, :town, :country,
                 :telephone, :email, :website, :is_rep, :rep_title, :rep_first_name, :rep_last_name, :rep_role, :rep_telephone, :rep_email,
                 :fund_deposit, :payment_method, :payments_count, :signing,
                 :ack_societaire, :ack_statuts, :ack_biens_communs, :ack_convocation, :person_type
  store_accessor :crm_data, :opportunity_id, :crm_history

  attr_accessor :signature_data

  before_save :compute_fields

  aasm column: 'status' do
    state :declared, initial: true
    state :confirmed

    event :confirm do
      transitions from: :declared, to: :confirmed
    end
  end

  def self.by_subscriber
    group("person_data -> 'email', category, label")
        .select("MIN(id) AS sub_id, MIN(created_at) AS creation_date, category, label, SUM(amount) AS total")
  end

  def to_param
    encrypt id
  end

  def shares_count
    amount.nil? ? 0 : (amount / 100).to_i
  end

  def amount_as_text
    "#{amount.humanize} euros" unless amount.nil?
  end

  def is_structure?
    category != 'sa' && category != 'sr'
  end

  def pp?
    person_type == 'pp'
  end

  def is_rep?
    is_rep == '1'
  end

  def email_recipient
    (!is_rep? && !rep_email.blank?) ? rep_email : email
  end

  def document_filename
    "Bulletin souscription - #{id} - #{pp? ? 'Personne physique' : 'Personne morale'} - #{public_label} - #{signed_at ? (I18n.l(signed_at, format: :doc) + ' - Signé') : 'Non signé'}".gsub('/', '-')
  end

  def compute_fields
    self.normalize_names
    self.label = normalize_label
    unless postal_code.blank?
      self.postal_code = postal_code.strip
      code = country == 'fr' ? lpad(postal_code) : (country.upcase + postal_code)
      REGIONS.each_pair do |r, codes|
        self.region = r if codes.any? {|c| code.start_with?(c)}
      end
    end
    self.is_rep = '1' if is_rep.nil?
    self.siret = normalize_siret
  end

  def normalize_siret
    siret.gsub(/\s/, '') unless siret.blank?
  end

  def normalize_label
    if com_enabled
      public_label
    else
      'Déclaration anonyme'
    end
  end

  def normalize_names
    [:first_name, :last_name, :rep_first_name, :rep_last_name].each do |n|
      self.send("#{n}=", normalize_name(send(n))) unless send(n).blank?
    end
  end

  def normalize_name(txt)
    txt.split('-').map {|t| t.capitalize}.join('-')
  end

  def public_label
    is_structure? ? structure_name.gsub(/office (de|du) tourisme/i, 'OT') : full_name
  end

  def full_name
    "#{title} #{first_name} #{last_name}"
  end

  def full_rep_name
    "#{rep_title} #{rep_first_name} #{rep_last_name}"
  end

  def emails
    [email, rep_email].select {|e| !e.blank?}
  end

  def lpad(str)
    str.length == 5 ? str : ('0' + str)
  end

  def legal_entity_type
    (legal_type == 'autre' ? legal_type_desc : LEGAL_TYPES[legal_type.to_sym][:label]) unless legal_type.blank?
  end

  def sponsor_label
    sponsor.label if sponsor
  end

  def last_crm_entry
    unless crm_history.blank?
      {timestamp: crm_history.keys.sort.last, statuses: crm_history[crm_history.keys.sort.last]}
    end
  end

  def opportunity_link
    "https://www.sellsy.fr/prospection/opportunities/#{opportunity_id}" unless opportunity_id.blank?
  end
end

app/controllers/admin/subscriptions_controller.rb
class Admin::SubscriptionsController < Admin::UserController
  before_action :check_credentials

  def index
    @subscriptions = Subscription.all.order(created_at: :desc)
  end

  def update
    @subscription = Subscription.find(Subscription.decrypt(params[:id]))
    if @subscription.update(subscription_params)
      flash[:notice] = "La souscription a bien été mise à jour."
    else
      flash[:alert] = "Une erreur s'est produite lors de la mise à jour de la souscription."
    end
  end

  def sync_crm
    @subscription = Subscription.find(Subscription.decrypt(params[:id]))
    begin
      CrmClient.add_or_update(@subscription)
      flash[:notice] = "La souscription a bien été enregistrée dans la base GRC."
    rescue StandardError => e
      logger.error "sync_crm failed : #{e.message}"
      logger.error e.backtrace[0..20].join("\n")
      flash[:alert] = "Une erreur s'est produite lors de l'enregistrement des la souscription dans la base GRC."
    end
  end

  def send_mail
    @subscription = Subscription.find(Subscription.decrypt(params[:id]))
    if params[:mailer_action] == 'confirm_subscription' || params[:mailer_action] == 'declare_subscription'
      SubscriptionsMailer.send(params[:mailer_action].to_sym, @subscription).deliver_now
      flash[:notice] = "L'email a bien été envoyé."
    else
      flash[:alert] = "Une erreur s'est produite lors de l'envoi de l'email."
    end
  end

  private

  def check_credentials
    authenticate_user!
    unless Rails.application.config.subscriptions_admins.include?(current_user.email)
      redirect_to root_url, alert: "Vous n'êtes pas autorisé(e) à accéder à cette page."
    end
  end

  def subscription_params
    params.require(:subscription).permit(:com_enabled)
  end
end

app/controllers/subscriptions_controller.rb
require "base64"

class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:edit, :update, :share, :widget, :update_widget, :show, :confirm, :document]
  skip_before_action :verify_authenticity_token, only: [:show]

  def index
    @subscriptions = Subscription.all.by_subscriber
  end

  def new
    @subscription = Subscription.new(person_type: 'pm', payments_count: 'single_payment', is_rep: "1")
  end

  def create
    @subscription = Subscription.new(subscription_params)
    handle_subscription_save(true, :new)
  end

  def edit
    if @subscription.confirmed?
      redirect_to url_for(action: :confirm)
    else
      @subscription.person_type ||= 'pm'
      @subscription.payments_count ||= 'single_payment'
    end
  end

  def update
    @subscription.attributes = subscription_params
    handle_subscription_save(false, :edit)
  end

  def update_widget
    unless params[:subscription][:widget_hosts].blank?
      hosts = params[:subscription][:widget_hosts].split(',').map {|h| h.strip.gsub(/https?:\/\//, '')}
      @success = @subscription.update(widget_hosts: hosts)
    end
  end

  def show
  end

  def members
    @members = []
    unless params[:pattern].blank?
      @members = ApidaeMember.lookup_by_name(params[:pattern])
    end
  end

  def member
    @member = ApidaeMember.find_by_apidae_id(params[:id])
    render json: @member.retrieve_info.merge(id: @member.apidae_id, name: @member.name)
  end

  def confirm
  end

  def rankings
    @subscriptions = filtered_records(Subscription.all.by_subscriber).order("sub_id DESC").limit(5)
    @max_amount = @subscriptions.to_a.map {|s| s.total}.max
  end

  def proportions
    default_map = Hash[CATEGORIES.keys.map {|cat| [cat.to_s, 0]}]
    records = filtered_records(Subscription.by_subscriber)
    @members_by_category = default_map.merge(Hash[records.to_a.group_by {|s| s.category }.map {|cat, subs| [cat, subs.length]}])
    @amount_by_category = default_map.merge(Hash[records.to_a.group_by {|s| s.category }.map {|cat, subs| [cat, subs.sum {|s| s.total}]}])
    render json: {subscriptions: @members_by_category, amounts: @amount_by_category}
  end

  def regions
    region_field = "COALESCE(NULLIF(region, ''), 'autres')"
    subs = params[:category].blank? ? Subscription.all : Subscription.where(category: params[:category])
    subs = subs.where("#{region_field} = ?", params[:region]) unless params[:region].blank?
    @amounts_by_region = Hash[subs.select("#{region_field} AS region_ref, SUM(amount) AS total").group(region_field)
                                    .map {|s| [s.region_ref, s.total]}]
    render json: @amounts_by_region
  end

  def share
    render :share, layout: 'standalone'
  end

  def widget
  end

  def document
    render :document, layout: 'print'
  end

  private

  def subscription_params
    params.require(:subscription).permit!
  end

  def set_subscription
    @subscription = Subscription.find(Subscription.decrypt(params[:id]))
  end

  def filtered_records(records)
    unless params[:filter].blank?
      records = records.where("category = ?", params[:filter])
    end
    unless params[:region].blank?
      records = records.where("COALESCE(NULLIF(region, ''), 'autres') = ?", params[:region])
    end
    records
  end

  def handle_subscription_save(new_sub, error_action)
    Rails.logger.info "Handling subscription save"
    unless @subscription.signature_data.blank?
      encoded_signature = @subscription.signature_data.split(",")[1]
      unless encoded_signature.blank?
        decoded_signature = Base64.decode64(encoded_signature)
        @subscription.signature.attach(io: StringIO.new(decoded_signature), filename: 'signature.png')
        Rails.logger.info "Subscription signature attached"
      end
    end
    if @subscription.save
      Rails.logger.info "Subscription saved"
      if new_sub
        SubscriptionsMailer.declare_subscription(@subscription).deliver_now
        Rails.logger.info "New sub - declare subscription sent"
        redirect_to confirm_subscription_url(@subscription)
      elsif @subscription.confirm!
        SubscriptionsMailer.confirm_subscription(@subscription).deliver_now
        Rails.logger.info "New sub - confirm subscription sent"
        redirect_to confirm_subscription_url(@subscription)
      else
        flash.now[:alert] = "Une erreur s'est produite lors de la confirmation de la souscription."
        render error_action
      end
    else
      flash.now[:alert] = "Une erreur s'est produite lors de l'enregistrement de la souscription."
      render error_action
    end
  end
end

app/helpers/admin/subscriptions_helper.rb
module Admin::SubscriptionsHelper
  def export_columns
    [:created_at, :status, :signed_at, :id, :label, :structure_name, :title, :first_name, :last_name, :category, :apidae_member_id,
     :amount, :siret, :legal_entity_type, :role, :address, :postal_code, :town, :country, :telephone, :email,
     :website, :fund_deposit, :payment_method, :com_enabled, :sponsor_label, :opportunity_link]
  end

  def export_values(subscription)
    vals = []
    export_columns.each do |col|
      if col == :category
        vals << CATEGORIES[subscription.send(col).to_sym][:name]
      elsif [:country, :fund_deposit, :status, :payment_method].include?(col)
        vals << (subscription.send(col).blank? ? '' : I18n.t("export.subscription.value.#{subscription.send(col)}"))
      else
        vals << subscription.send(col)
      end
    end
    vals
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def subscription_categories
    CATEGORIES.map {|ref, cat| [cat[:name], ref.to_s]}
  end

  def subscription_countries
    [
        ['France', 'fr'],
        ['Suisse', 'ch'],
        ['Allemagne', 'de'],
        ['Italie', 'it'],
        ['Espagne', 'es'],
        ['Belgique', 'be'],
        ['Royaume-Uni', 'gb']
    ]
  end

  def subscription_titles
    ['M.', 'Mme']
  end

  def legal_types
    LEGAL_TYPES.map {|ref, lt| [lt[:label], ref.to_s]}
  end

  def subscription_sponsors
    Subscription.where(com_enabled: true).by_subscriber.to_a.sort_by {|s| s.label}.map {|s| [s.label, s.sub_id]}
  end

  def deposit_choices
    [
        ['Avant le 16/03/2020', 'before'],
        ['Après le 16/03/2020', 'after'],
        ['Ne sait pas', 'unavailable']
    ]
  end

  def chk(field, checked_value)
    "<i class=\"u-big apidae-icon-#{@subscription.send(field) == checked_value ? 'validate' : 'hexa'}\"></i>".html_safe
  end

  def address_fields
    @subscription.address.split(/(\r\n?)/)
  end

  def phase_label
    @subscription.persisted? && @subscription.declared? ? "souscription" : "déclaration d'intention"
  end

  def render_crm_status(status)
    if status
      "OK" + (status.is_a?(Integer) ? " (#{status})" : '')
    else
      "KO"
    end
  end
end

app/views/subscriptions/_contact_form.html.erb
<div class="flex-container mtm mbs person_pm_only">
  <div class="txtright item-center w40 prs pls"><i class="fas fa-chevron-circle-right txt--primary u-bigger"></i></div>
  <div class="w60 lh"><%= contact_title %></div>
</div>
<div class="flex-container mbs">
  <div class="txtright item-center w40 prs pls"><%= f.label :"#{prefix}title", 'Civilité<sup>*</sup>'.html_safe %></div>
  <div class="w60">
    <%= f.select(:"#{prefix}title", subscription_titles, {prompt: 'Sélectionnez une civilité'}, required: true, class: 'w100') %>
  </div>
</div>
<div class="flex-container mbs">
  <div class="txtright item-center w40 prs pls"><%= f.label :"#{prefix}last_name", 'Nom<sup>*</sup>'.html_safe %></div>
  <div class="w60">
    <%= f.text_field :"#{prefix}last_name", class: 'w100', required: true, placeholder: placeholder %>
  </div>
</div>
<div class="flex-container mbs">
  <div class="txtright item-center w40 prs pls"><%= f.label :"#{prefix}first_name", 'Prénom<sup>*</sup>'.html_safe %></div>
  <div class="w60">
    <%= f.text_field :"#{prefix}first_name", class: 'w100', required: true, placeholder: placeholder %>
  </div>
</div>
<% if prefix.blank? %>
  <div class="flex-container mbs person_pp_only">
    <div class="txtright item-center w40 prs pls"><%= f.label :birth_date, 'Date de naissance<sup>*</sup>'.html_safe %></div>
    <div class="w60">
      <%= f.date_field :birth_date, value: f.object.birth_date,
                       class: 'w100', required: true, placeholder: 'JJ/MM/AAAA' %>
    </div>
  </div>
<% end %>
<div class="flex-container mbs">
  <div class="txtright item-center w40 prs pls"><%= f.label :"#{prefix}role", 'Fonction<sup>*</sup>'.html_safe %></div>
  <div class="w60">
    <%= f.text_field :"#{prefix}role", class: 'w100', required: true %>
  </div>
</div>
<div class="flex-container mbs">
  <div class="txtright item-center w40 prs pls"><%= f.label :"#{prefix}telephone", 'Téléphone<sup>*</sup>'.html_safe %></div>
  <div class="w60">
    <%= f.text_field :"#{prefix}telephone", class: 'w100', required: true, placeholder: 'portable de préférence' %>
  </div>
</div>
<div class="flex-container mbs">
  <div class="txtright item-center w40 prs pls"><%= f.label :"#{prefix}email", 'Email<sup>*</sup>'.html_safe %></div>
  <div class="w60">
    <%= f.email_field :"#{prefix}email", class: 'w100', required: true %>
  </div>
</div>

app/views/subscriptions/_empty_code.html.erb
<h3 class="flex-container--row mtl">
  <i class="fas fa-chevron-circle-right txt--warning u-big prvs"></i><span>Code d'intégration</span>
</h3>
<p class="txtcenter">Veuillez saisir au moins un nom de domaine pour obtenir le code d'intégration.</p>

app/views/subscriptions/_widget_code.html.erb
<h3 class="flex-container--row mtl">
  <i class="fas fa-chevron-circle-right txt--warning u-big prvs"></i><span>Code d'intégration</span>
</h3>
<% snippet = capture do %>
  <script src="<%= subscription_url(id: @subscription.id, format: :js) %>" async></script>
  <div id="apidae_subscription_widget"></div>
<% end %>
<div class="flex-container w100 mtm">
  <div class="item-fluid">
    <code id="widget_integration_code" class="u-small"><%= raw escape_once snippet %></code>
  </div>
  <div>
    <button class="apidae_btn_outline" onclick="copyCode()"><i class="fas fa-copy prvs"></i>Copier</button>
  </div>
  <p class="lh ptvs">
    <small>
      <i class="fas fa-info-circle prvs"></i>Ce code doit être "copié-collé" dans la page de votre site web qui
      accueillera le widget. Il peut être inséré tel quel ou réparti dans différentes sections du site :
      typiquement, la balise &lt;script&gt;...&lt;/script&gt; pourra être insérée dans l'entête du site, alors que la
      balise &lt;div id="apidae_subscription_widget"&gt;&lt;/div&gt; sera à positionner dans votre page à l'endroit où le widget doit s'afficher.
    </small>
  </p>
</div>

app/views/subscriptions/confirm.html.erb
<% content_for :page_styles do %>
  <%= stylesheet_link_tag 'subscription', media: 'all' %>
<% end %>

<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v5.0"></script>
<script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: fr_FR</script>

<section id="confirm_subscription" class="bg--primary">
  <div id="confirmation_wrapper">
    <div class="w100 mw1140p center pam">
      <% if @subscription.persisted? && @subscription.declared? %>
        <h1 class="txtcenter txt--white mtl mbl h2-like">Merci pour votre déclaration</h1>
        <div id="confirmation_content" class="bg--white">
          <h3 class="flex-container--row">
            <i class="fas fa-chevron-circle-right txt--warning u-big prvs"></i><span>Confirmation de ma déclaration d'intention</span>
          </h3>
          <p class="txtcenter mtl">
            Merci pour votre déclaration. Une confirmation vous a été envoyée par mail.<br/><br/>
            Vérifiez si vous êtes dans le top 5 des déclarations d’intention et partagez la bonne nouvelle !
          </p>
          <div class="mtm">
            <iframe class="video_iframe w75 center" src="https://www.youtube-nocookie.com/embed/YHicKE5zbBc" title="Apidae Tourisme" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          </div>
        </div>
      <% else %>
        <h1 class="txtcenter txt--white mtl mbl h2-like">Merci pour votre souscription !</h1>
        <div id="confirmation_content" class="bg--white">
          <h3 class="flex-container--row">
            <i class="fas fa-chevron-circle-right txt--warning u-big prvs"></i><span>Confirmation de ma souscription</span>
          </h3>
          <p class="txtcenter mtl">
            Merci pour votre souscription. Une confirmation vous a été envoyée par mail.<br/>
            <% if @subscription.payment_method == 'cheque' %>
              Merci de libeller votre chèque à l’ordre de Apidae Tourisme Scic SA et de l’envoyer avec une copie de ce bulletin à : Apidae Tourisme, Now Coworking, 35 rue de Marseille, 69007 Lyon
            <% else %>
              Merci de réaliser votre virement sur le compte de Apidae Tourisme Scic SA (<a href="/rib-scic-sa-apidae-tourisme.pdf" target="_blank">télécharger le RIB</a>) en précisant comme intitulé de virement « Souscription n°XXX », X étant le n° de souscription présent sur votre bulletin.
            <% end %>
            <br/>
            <br/>
            <br/>
            <a class="apidae_btn_solid" target="_blank" href="https://print.souscription.apidae-tourisme.com/souscription?path=<%= CGI.escape(document_subscription_url(@subscription, host: Rails.application.default_url_options[:host])) %>">Télécharger votre bulletin de souscription</a><br/>
            <br/>
            <br/>
            <br/>
            <a class="apidae_btn_outline" href="/" target="_blank">Vérifiez si vous êtes dans le top 5 des déclarations d’intention et partagez la bonne nouvelle !</a>
          </p>
        </div>
      <% end %>
      <div class="flex-container--row mtm jcc">
        <div class="fb-share-button mls" data-href="<%= share_subscription_url(@subscription) %>" data-layout="button" data-size="large">
          <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<%= CGI.escape(share_subscription_url(@subscription)) %>&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Partager sur Facebook</a>
        </div>
        <div class="mls">
          <script type="IN/Share" data-url="<%= share_subscription_url(@subscription) %>"></script>
        </div>
      </div>
    </div>
  </div>
</section>

<% content_for :page_scripts do %>
  <script>
      window.twttr = (function (d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0],
              t = window.twttr || {};
          if (d.getElementById(id)) return t;
          js = d.createElement(s);
          js.id = id;
          js.src = "https://platform.twitter.com/widgets.js";
          fjs.parentNode.insertBefore(js, fjs);

          t._e = [];
          t.ready = function (f) {
              t._e.push(f);
          };

          return t;
      }(document, "script", "twitter-wjs"));
  </script>
<% end %>

app/views/subscriptions/edit.html.erb
<section id="edit_subscription" class="bg--primary">
  <div id="form_wrapper">
    <div class="w100 mw1140p center pam">
      <h1 class="txtcenter txt--white mtl mbl h2-like">Je prends des parts au capital</h1>
      <%= render "form" %>
    </div>
  </div>
</section>

app/views/subscriptions/new.html.erb
<section id="new_subscription">
  <div id="form_wrapper">
    <div class="w100 mw1140p center pam">
      <h1 class="txtcenter txt--white mtl mbl h2-like">Je prends des parts au capital</h1>
      <%= render "form" %>
    </div>
  </div>
</section>
<% content_for :page_scripts do %>
  <script>
      var formatAmount = d3.formatLocale({decimal: ',', thousands: ' ', grouping: [3], currency: ['', ' €']}).format('$,');
  </script>
<% end %>

app/views/subscriptions/share.html.erb
<div class="txtcenter w40 center pal small-w66 tiny-w100 txt--white">
  <%= image_tag 'logo_apidae_h.png', class: 'w50' %>
  <p class="mtm mbm lh fw500">
    Le réseau évolue...<br/>
    <br/>
    Apidae Tourisme, Scic SA à capital variable sera mise en place au printemps 2020.<br/>
    <br/>
    Prenez des parts sociales au capital,<br/>
    parrainez et remportez vos badges<br/>
    bronze, argent et or !
  </p>
  <%= image_tag 'badge-pionnier-apidae.png', alt: 'badge pionnier apidae', class: 'w60' %>
  <div>
    <a href="/" class="apidae_btn_solid btn--big mtm mbl">Rejoignez l’aventure !</a>
  </div>
</div>

app/views/subscriptions/show.js.erb
var widgetContainer = document.querySelector("#apidae_subscription_widget");
if (widgetContainer) {
    widgetContainer.innerHTML = '<div style="text-align: center;"><img src="<%= image_url('badge-pionnier-apidae.png') %>" alt="badge pionnier apidae" style="width: 100%; max-width: 120px; height: auto;"><br/><a href="<%= root_url %>" target="_blank">Rejoignez l\'aventure !</a>'
}

app/views/subscriptions/update.js.erb
<% if @success %>
  var wrapper = document.querySelector("#widget_code");
  if (wrapper) {
      wrapper.innerHTML = '<%= j(render "widget_code") %>';
  }
<% else %>
  console.log('failed');
<% end %>

app/views/subscriptions/update_widget.js.erb
<% if @success %>
  var wrapper = document.querySelector("#widget_code");
  if (wrapper) {
      wrapper.innerHTML = '<%= j(render "widget_code") %>';
  }
<% else %>
  console.log('failed');
<% end %>

app/views/subscriptions/widget.html.erb
<section id="widget_creation" class="bg--primary">
  <div id="confirmation_wrapper">
    <div class="w100 mw1140p center pam">
      <h1 class="txtcenter txt--white mtl mbl h2-like">Widget de souscription</h1>
      <div id="widget_content" class="bg--white">
        <h3 class="flex-container--row">
          <i class="fas fa-chevron-circle-right txt--warning u-big prvs"></i><span>Générer mon widget</span>
        </h3>
        <p class="txtcenter mts">
          Vous pouvez créer un widget qui affichera automatiquement vos badges pionniers obtenus au lors de la levée de
          fonds de Apidae Tourisme, Scic SA à capital variable. Pour cela, merci de saisir ci-dessous les urls des sites (adresses) sur
          lesquels vous voulez afficher le widget et cliquez sur le bouton "Récupérer le code". Il vous suffit ensuite
          de demander à votre webmaster d’intégrer ce code sur votre (vos) site(s).
        </p>
        <%= form_for(@subscription, url: { action: "update_widget" }, remote: true, html: {id: 'widget_form'}) do |f| %>
          <div class="txtcenter mtm">
            <div><%= f.label :widget_hosts, 'Adresses des sites web hôtes<sup>*</sup>'.html_safe, class: 'w100 fw500' %></div>
            <div>
              <%= f.text_field :widget_hosts, class: 'w100', required: true, placeholder: 'Séparées par des virgules, ex : www.monsite1.fr, www.monsite2.com' %>
            </div>
          </div>
          <div class="mtm mbs txtcenter">
            <%= f.submit "Récupérer le code", class: 'apidae_btn_warning', data: { disable_with: "Génération du code..." } %>
          </div>
        <% end %>
        <div id="widget_code">
        </div>
      </div>
    </div>
  </div>
</section>

<% content_for :page_scripts do %>
  <script>
      function copyCode() {
          var codeElt = document.querySelector("#widget_integration_code");
          if (document.body.createTextRange) {
              var range = document.body.createTextRange();
              range.moveToElementText(codeElt);
              range.select();
          } else if (window.getSelection) {
              var selection = window.getSelection();
              var range = document.createRange();
              range.selectNodeContents(codeElt);
              selection.removeAllRanges();
              selection.addRange(range);
          } else {
              console.warn("copyCode - Unsupported browser");
          }
          document.execCommand("copy");
      }
  </script>
<% end %>