config/routes.rb
Rails.application.routes.draw do

  get 'souscrire', to: 'subscriptions#new'
  get 'comment-souscrire', to: redirect('/pourquoi-souscrire')

  resources :subscriptions, only: [:index, :new, :create, :edit, :update, :show], path: 'souscriptions' do
    get :confirm, on: :member, path: 'confirmation'
    get :document, on: :member, path: 'bulletin'
    get :members, on: :collection
    get :member, on: :collection
    get :rankings, on: :collection
    get :proportions, on: :collection
    get :regions, on: :collection
    get :share, on: :member, path: 'partager'
    get :widget, on: :member
    patch :update_widget, on: :member
  end

  devise_for :users, path: 'administration', controllers: {omniauth_callbacks: 'users/omniauth_callbacks'},
             path_names: {sign_in: 'connexion', sign_out: 'deconnexion'}

  scope module: 'admin' do
    scope '/administration' do
      resources :subscriptions, only: [:index, :update], path: 'souscriptions', as: 'subs' do
        get :sync_crm, on: :member
        post :send_mail, on: :member
      end
    end
  end

  mount Sibu::Engine, at: '/'

  root to: redirect('/404.html')
end

app/models/subscription.rb
require 'sellsy'

class Subscription < ApplicationRecord
  include AASM
  include Obfuscable

  has_one_attached :signature
  has_many :sponsored, class_name: "Subscription", foreign_key: :sponsor_id
  belongs_to :sponsor, class_name: "Subscription", optional: true

  store_accessor :structure_data, :structure_name, :siret, :ape, :legal_type, :legal_type_desc, :apidae_member_id, :widget_hosts
  store_accessor :person_data, :title, :first_name, :last_name, :role, :birth_date, :address, :postal_code, :town, :country,
                 :telephone, :email, :website, :is_rep, :rep_title, :rep_first_name, :rep_last_name, :rep_role, :rep_telephone, :rep_email,
                 :fund_deposit, :payment_method, :payments_count, :signing,
                 :ack_societaire, :ack_statuts, :ack_biens_communs, :ack_convocation, :person_type
  store_accessor :crm_data, :opportunity_id, :crm_history

  attr_accessor :signature_data

  before_save :compute_fields

  aasm column: 'status' do
    state :declared, initial: true
    state :confirmed

    event :confirm do
      transitions from: :declared, to: :confirmed
    end
  end

  def self.by_subscriber
    group("person_data -> 'email', category, label")
        .select("MIN(id) AS sub_id, MIN(created_at) AS creation_date, category, label, SUM(amount) AS total")
  end

  def to_param
    encrypt id
  end

  def shares_count
    amount.nil? ? 0 : (amount / 100).to_i
  end

  def amount_as_text
    "#{amount.humanize} euros" unless amount.nil?
  end

  def is_structure?
    category != 'sa' && category != 'sr'
  end

  def pp?
    person_type == 'pp'
  end

  def is_rep?
    is_rep == '1'
  end

  def email_recipient
    (!is_rep? && !rep_email.blank?) ? rep_email : email
  end

  def document_filename
    "Bulletin souscription - #{id} - #{pp? ? 'Personne physique' : 'Personne morale'} - #{public_label} - #{signed_at ? (I18n.l(signed_at, format: :doc) + ' - Signé') : 'Non signé'}".gsub('/', '-')
  end

  def compute_fields
    self.normalize_names
    self.label = normalize_label
    unless postal_code.blank?
      self.postal_code = postal_code.strip
      code = country == 'fr' ? lpad(postal_code) : (country.upcase + postal_code)
      REGIONS.each_pair do |r, codes|
        self.region = r if codes.any? {|c| code.start_with?(c)}
      end
    end
    self.is_rep = '1' if is_rep.nil?
    self.siret = normalize_siret
  end

  def normalize_siret
    siret.gsub(/\s/, '') unless siret.blank?
  end

  def normalize_label
    if com_enabled
      public_label
    else
      'Déclaration anonyme'
    end
  end

  def normalize_names
    [:first_name, :last_name, :rep_first_name, :rep_last_name].each do |n|
      self.send("#{n}=", normalize_name(send(n))) unless send(n).blank?
    end
  end

  def normalize_name(txt)
    txt.split('-').map {|t| t.capitalize}.join('-')
  end

  def public_label
    is_structure? ? structure_name.gsub(/office (de|du) tourisme/i, 'OT') : full_name
  end

  def full_name
    "#{title} #{first_name} #{last_name}"
  end

  def full_rep_name
    "#{rep_title} #{rep_first_name} #{rep_last_name}"
  end

  def emails
    [email, rep_email].select {|e| !e.blank?}
  end

  def lpad(str)
    str.length == 5 ? str : ('0' + str)
  end

  def legal_entity_type
    (legal_type == 'autre' ? legal_type_desc : LEGAL_TYPES[legal_type.to_sym][:label]) unless legal_type.blank?
  end

  def sponsor_label
    sponsor.label if sponsor
  end

  def last_crm_entry
    unless crm_history.blank?
      {timestamp: crm_history.keys.sort.last, statuses: crm_history[crm_history.keys.sort.last]}
    end
  end

  def opportunity_link
    "https://www.sellsy.fr/prospection/opportunities/#{opportunity_id}" unless opportunity_id.blank?
  end
end

app/controllers/admin/subscriptions_controller.rb
class Admin::SubscriptionsController < Admin::UserController
  before_action :check_credentials

  def index
    @subscriptions = Subscription.all.order(created_at: :desc)
  end

  def update
    @subscription = Subscription.find(Subscription.decrypt(params[:id]))
    if @subscription.update(subscription_params)
      flash[:notice] = "La souscription a bien été mise à jour."
    else
      flash[:alert] = "Une erreur s'est produite lors de la mise à jour de la souscription."
    end
  end

  def sync_crm
    @subscription = Subscription.find(Subscription.decrypt(params[:id]))
    begin
      CrmClient.add_or_update(@subscription)
      flash[:notice] = "La souscription a bien été enregistrée dans la base GRC."
    rescue StandardError => e
      logger.error "sync_crm failed : #{e.message}"
      logger.error e.backtrace[0..20].join("\n")
      flash[:alert] = "Une erreur s'est produite lors de l'enregistrement des la souscription dans la base GRC."
    end
  end

  def send_mail
    @subscription = Subscription.find(Subscription.decrypt(params[:id]))
    if params[:mailer_action] == 'confirm_subscription' || params[:mailer_action] == 'declare_subscription'
      SubscriptionsMailer.send(params[:mailer_action].to_sym, @subscription).deliver_now
      flash[:notice] = "L'email a bien été envoyé."
    else
      flash[:alert] = "Une erreur s'est produite lors de l'envoi de l'email."
    end
  end

  private

  def check_credentials
    authenticate_user!
    unless Rails.application.config.subscriptions_admins.include?(current_user.email)
      redirect_to root_url, alert: "Vous n'êtes pas autorisé(e) à accéder à cette page."
    end
  end

  def subscription_params
    params.require(:subscription).permit(:com_enabled)
  end
end

app/controllers/subscriptions_controller.rb
require "base64"

class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:edit, :update, :share, :widget, :update_widget, :show, :confirm, :document]
  skip_before_action :verify_authenticity_token, only: [:show]

  def index
    @subscriptions = Subscription.all.by_subscriber
  end

  def new
    @subscription = Subscription.new(person_type: 'pm', payments_count: 'single_payment', is_rep: "1")
  end

  def create
    @subscription = Subscription.new(subscription_params)
    handle_subscription_save(true, :new)
  end

  def edit
    if @subscription.confirmed?
      redirect_to url_for(action: :confirm)
    else
      @subscription.person_type ||= 'pm'
      @subscription.payments_count ||= 'single_payment'
    end
  end

  def update
    @subscription.attributes = subscription_params
    handle_subscription_save(false, :edit)
  end

  def update_widget
    unless params[:subscription][:widget_hosts].blank?
      hosts = params[:subscription][:widget_hosts].split(',').map {|h| h.strip.gsub(/https?:\/\//, '')}
      @success = @subscription.update(widget_hosts: hosts)
    end
  end

  def show
  end

  def members
    @members = []
    unless params[:pattern].blank?
      @members = ApidaeMember.lookup_by_name(params[:pattern])
    end
  end

  def member
    @member = ApidaeMember.find_by_apidae_id(params[:id])
    render json: @member.retrieve_info.merge(id: @member.apidae_id, name: @member.name)
  end

  def confirm
  end

  def rankings
    @subscriptions = filtered_records(Subscription.all.by_subscriber).order("sub_id DESC").limit(5)
    @max_amount = @subscriptions.to_a.map {|s| s.total}.max
  end

  def proportions
    default_map = Hash[CATEGORIES.keys.map {|cat| [cat.to_s, 0]}]
    records = filtered_records(Subscription.by_subscriber)
    @members_by_category = default_map.merge(Hash[records.to_a.group_by {|s| s.category }.map {|cat, subs| [cat, subs.length]}])
    @amount_by_category = default_map.merge(Hash[records.to_a.group_by {|s| s.category }.map {|cat, subs| [cat, subs.sum {|s| s.total}]}])
    render json: {subscriptions: @members_by_category, amounts: @amount_by_category}
  end

  def regions
    region_field = "COALESCE(NULLIF(region, ''), 'autres')"
    subs = params[:category].blank? ? Subscription.all : Subscription.where(category: params[:category])
    subs = subs.where("#{region_field} = ?", params[:region]) unless params[:region].blank?
    @amounts_by_region = Hash[subs.select("#{region_field} AS region_ref, SUM(amount) AS total").group(region_field)
                                    .map {|s| [s.region_ref, s.total]}]
    render json: @amounts_by_region
  end

  def share
    render :share, layout: 'standalone'
  end

  def widget
  end

  def document
    render :document, layout: 'print'
  end

  private

  def subscription_params
    params.require(:subscription).permit!
  end

  def set_subscription
    @subscription = Subscription.find(Subscription.decrypt(params[:id]))
  end

  def filtered_records(records)
    unless params[:filter].blank?
      records = records.where("category = ?", params[:filter])
    end
    unless params[:region].blank?
      records = records.where("COALESCE(NULLIF(region, ''), 'autres') = ?", params[:region])
    end
    records
  end

  def handle_subscription_save(new_sub, error_action)
    Rails.logger.info "Handling subscription save"
    unless @subscription.signature_data.blank?
      encoded_signature = @subscription.signature_data.split(",")[1]
      unless encoded_signature.blank?
        decoded_signature = Base64.decode64(encoded_signature)
        @subscription.signature.attach(io: StringIO.new(decoded_signature), filename: 'signature.png')
        Rails.logger.info "Subscription signature attached"
      end
    end
    if @subscription.save
      Rails.logger.info "Subscription saved"
      if new_sub
        SubscriptionsMailer.declare_subscription(@subscription).deliver_now
        Rails.logger.info "New sub - declare subscription sent"
        redirect_to confirm_subscription_url(@subscription)
      elsif @subscription.confirm!
        SubscriptionsMailer.confirm_subscription(@subscription).deliver_now
        Rails.logger.info "New sub - confirm subscription sent"
        redirect_to confirm_subscription_url(@subscription)
      else
        flash.now[:alert] = "Une erreur s'est produite lors de la confirmation de la souscription."
        render error_action
      end
    else
      flash.now[:alert] = "Une erreur s'est produite lors de l'enregistrement de la souscription."
      render error_action
    end
  end
end

app/helpers/admin/subscriptions_helper.rb
module Admin::SubscriptionsHelper
  def export_columns
    [:created_at, :status, :signed_at, :id, :label, :structure_name, :title, :first_name, :last_name, :category, :apidae_member_id,
     :amount, :siret, :legal_entity_type, :role, :address, :postal_code, :town, :country, :telephone, :email,
     :website, :fund_deposit, :payment_method, :com_enabled, :sponsor_label, :opportunity_link]
  end

  def export_values(subscription)
    vals = []
    export_columns.each do |col|
      if col == :category
        vals << CATEGORIES[subscription.send(col).to_sym][:name]
      elsif [:country, :fund_deposit, :status, :payment_method].include?(col)
        vals << (subscription.send(col).blank? ? '' : I18n.t("export.subscription.value.#{subscription.send(col)}"))
      else
        vals << subscription.send(col)
      end
    end
    vals
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def subscription_categories
    CATEGORIES.map {|ref, cat| [cat[:name], ref.to_s]}
  end

  def subscription_countries
    [
        ['France', 'fr'],
        ['Suisse', 'ch'],
        ['Allemagne', 'de'],
        ['Italie', 'it'],
        ['Espagne', 'es'],
        ['Belgique', 'be'],
        ['Royaume-Uni', 'gb']
    ]
  end

  def subscription_titles
    ['M.', 'Mme']
  end

  def legal_types
    LEGAL_TYPES.map {|ref, lt| [lt[:label], ref.to_s]}
  end

  def subscription_sponsors
    Subscription.where(com_enabled: true).by_subscriber.to_a.sort_by {|s| s.label}.map {|s| [s.label, s.sub_id]}
  end

  def deposit_choices
    [
        ['Avant le 16/03/2020', 'before'],
        ['Après le 16/03/2020', 'after'],
        ['Ne sait pas', 'unavailable']
    ]
  end

  def chk(field, checked_value)
    "<i class=\"u-big apidae-icon-#{@subscription.send(field) == checked_value ? 'validate' : 'hexa'}\"></i>".html_safe
  end

  def address_fields
    @subscription.address.split(/(\r\n?)/)
  end

  def phase_label
    @subscription.persisted? && @subscription.declared? ? "souscription" : "déclaration d'intention"
  end

  def render_crm_status(status)
    if status
      "OK" + (status.is_a?(Integer) ? " (#{status})" : '')
    else
      "KO"
    end
  end
end

app/views/admin/subscriptions/_subscription_entry.html.erb
<td><span class="is-hidden"><%= s.created_at.to_i %></span><%= l(s.created_at, format: :detailed) %></td>
<td class="lh"><span class="fw500"><%= s.public_label %></span><br/><%= s.email %></td>
<td><%= s.id %></td>
<td><%= s.com_enabled ? 'Non' : 'Oui' %></td>
<td><%= s.amount %></td>
<td><%= CATEGORIES[s.category.to_sym][:name] %></td>
<td><%= t("export.subscription.status.#{s.status}") %></td>
<td>
  <%= link_to "<i class=\"fas u-bigger fa-eye#{'-slash' if s.com_enabled}\"></i>".html_safe,
              sub_path(s, 'subscription[com_enabled]': (s.com_enabled ? '0' : '1')),
              method: :patch, remote: true,
              data: {confirm: "#{s.com_enabled ? 'Anonymiser' : 'Rendre publique'} cette déclaration ?"},
              class: "btn btn--info",
              title: (s.com_enabled ? 'Anonymiser' : 'Rendre publique') %>
  <%= link_to "<i class=\"fas u-bigger fa-file-alt\"></i>".html_safe, document_subscription_path(s),
              target: '_blank', class: 'btn btn--info' %>
  <%= link_to "<i class=\"fas u-bigger fa-envelope\"></i>".html_safe, send_mail_sub_path(s, mailer_action: s.confirmed? ? 'confirm_subscription' : 'declare_subscription'),
              method: :post, remote: true,
              data: {confirm: "Envoyer à nouveau la confirmation #{s.confirmed? ? "de souscription" : "de déclaration d'intention"} ?"},
              class: 'btn btn--info' %>
  <%= link_to "<i class=\"fas u-bigger fa-pen-square\"></i>".html_safe, edit_subscription_url(s),
              target: '_blank', class: 'btn btn--info', disabled: s.confirmed? %>
</td>

app/views/admin/subscriptions/index.html.erb
<div class="flex-container pbs">
  <h1 class="txtleft item-fluid u-uppercase">Souscriptions</h1>
  <div class="w120p item-center">
    <%= link_to 'Export Excel', '/administration/souscriptions.xlsx', class: 'btn btn--primary', target: '_blank' %>
  </div>
</div>
<div class="mts">
  <table id="subscriptions_table" class="data_table table--zebra">
    <thead class="bg--inverse">
    <tr class="txtcenter">
      <th class="w100p">Date</th>
      <th class="w300p">Nom</th>
      <th>Réf.</th>
      <th>Anonyme</th>
      <th>Montant</th>
      <th>Catégorie</th>
      <th>Statut</th>
      <th class="w200p"></th>
    </tr>
    </thead>
    <tbody class="u-smaller">
    <% if @subscriptions.any? %>
      <% @subscriptions.each do |s| %>
        <tr class="txtcenter" id="sub_<%= s.id %>">
          <%= render 'subscription_entry', s: s %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="8" class="txtcenter pas">
          Aucune souscription pour le moment.
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% content_for :page_scripts do %>
  <script>
      document.addEventListener("DOMContentLoaded", function (event) {
          initializeDatatable("#subscriptions_table", 0);
      });
  </script>
<% end %>

app/views/admin/subscriptions/send_mail.js.erb
document.querySelector("#notifs").innerHTML = "<%= j(render 'shared/notifications') %>";
displayAlerts();

app/views/admin/subscriptions/update.js.erb
var subEntry = document.querySelector("#sub_<%= @subscription.id %>");
if (subEntry) {
    subEntry.innerHTML = "<%= j(render 'subscription_entry', s: @subscription) %>";
}
document.querySelector("#notifs").innerHTML = "<%= j(render 'shared/notifications') %>";
displayAlerts();